/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FATİH
 */
public class yaallahbs extends javax.swing.JFrame {

    /**
     * Creates new form yaallahbs
     */
    public yaallahbs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cevirileceksayi = new javax.swing.JTextField();
        cevirilensayi = new javax.swing.JTextField();
        rb2den10 = new javax.swing.JRadioButton();
        rb8den10 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rb16dan10 = new javax.swing.JRadioButton();
        rb10dan8 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rb10dan2 = new javax.swing.JRadioButton();
        rb10dan16 = new javax.swing.JRadioButton();
        tumlemetxt = new javax.swing.JTextField();
        tumlemesonuctxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sayibir2tbntxt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        sonuc2tbntxt = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sayiiki2tbntxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rbbcd = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        bcdgirilentxt = new javax.swing.JTextField();
        bcdsonuctxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rbexcess = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("ÇEVİRME İŞLEMİ İÇİN TIKLAYINIZ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 150, 220, 30);

        jLabel1.setText("ÇEVRİLECEK SAYIYI TABANA UYGUN SAYI OLARAK GİRİNİZ :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 360, 20);
        getContentPane().add(cevirileceksayi);
        cevirileceksayi.setBounds(120, 120, 85, 30);
        getContentPane().add(cevirilensayi);
        cevirilensayi.setBounds(430, 120, 90, 30);

        buttonGroup1.add(rb2den10);
        rb2den10.setText("2 den 10 a çevir");
        getContentPane().add(rb2den10);
        rb2den10.setBounds(20, 40, 130, 23);

        buttonGroup1.add(rb8den10);
        rb8den10.setText("8 den 10 a çevir");
        getContentPane().add(rb8den10);
        rb8den10.setBounds(160, 40, 130, 23);

        jLabel2.setText("ÇEVİRİLMİŞ SONUÇ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 90, 120, 30);

        jLabel3.setText("==>>ÇEVİRİLDİ==>>");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 130, 121, 17);

        buttonGroup1.add(rb16dan10);
        rb16dan10.setText("16 dan 10 a çevir");
        getContentPane().add(rb16dan10);
        rb16dan10.setBounds(300, 40, 130, 23);

        buttonGroup1.add(rb10dan8);
        rb10dan8.setText("10 dan 8 e çevir");
        getContentPane().add(rb10dan8);
        rb10dan8.setBounds(160, 70, 130, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ÇEVİRMEK İSTEDİĞİNİZ İŞLEMİ SEÇİP ÇEVİRİLİCEK SAYIYI GİRİNİZ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 10, 501, 17);

        buttonGroup1.add(rb10dan2);
        rb10dan2.setText("10 dan 2ye çevir");
        getContentPane().add(rb10dan2);
        rb10dan2.setBounds(20, 70, 130, 23);

        buttonGroup1.add(rb10dan16);
        rb10dan16.setText("10 dan 16 ya çevir");
        getContentPane().add(rb10dan16);
        rb10dan16.setBounds(300, 70, 130, 23);
        getContentPane().add(tumlemetxt);
        tumlemetxt.setBounds(180, 250, 90, 30);
        getContentPane().add(tumlemesonuctxt);
        tumlemesonuctxt.setBounds(420, 250, 100, 30);

        jLabel5.setText("SONUÇ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 230, 60, 14);

        jLabel6.setText("TÜMLENECEK SAYIYI GİRİNİZ :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 260, 190, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("TÜMLEME İŞLEMLERİ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 220, 152, 17);

        jButton2.setText("1'e tümleme");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(285, 250, 120, 23);

        jButton3.setText("2'ye tümleme");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(285, 280, 120, 23);

        jLabel8.setText("ÖRNEK: 2 TABANI İÇİN 1010 GİBİ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 160, 200, 14);

        jLabel9.setText("( Örn: ''5'' gibi)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 280, 90, 14);
        getContentPane().add(sayibir2tbntxt);
        sayibir2tbntxt.setBounds(680, 70, 110, 30);

        jButton4.setText("TOPLA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(720, 150, 80, 30);
        getContentPane().add(sonuc2tbntxt);
        sonuc2tbntxt.setBounds(780, 110, 90, 30);

        jButton5.setText("ÇIKAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(850, 150, 70, 30);

        jLabel10.setText("2 tabanlı 1. sayı");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(690, 50, 90, 14);

        jLabel11.setText("2 tabanlı 2.sayı");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(850, 50, 110, 14);

        jLabel12.setText("SONUÇ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(720, 120, 60, 14);

        jLabel13.setText("+ -");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(810, 70, 40, 20);
        getContentPane().add(sayiiki2tbntxt);
        sayiiki2tbntxt.setBounds(850, 70, 100, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("2 TABANINDA TOPLAMA VE ÇIKARMA İŞLEMİ İÇİN SAYILARI GİRİNİZ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(580, 10, 460, 20);

        buttonGroup2.add(rbbcd);
        rbbcd.setText("Sayıyı BCD koda çevir");
        getContentPane().add(rbbcd);
        rbbcd.setBounds(630, 240, 140, 23);

        jButton6.setText("ÇEVİR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(780, 330, 90, 40);
        getContentPane().add(bcdgirilentxt);
        bcdgirilentxt.setBounds(700, 290, 110, 30);
        getContentPane().add(bcdsonuctxt);
        bcdsonuctxt.setBounds(870, 290, 120, 30);

        jLabel15.setText("SAYIYI GİRİNİZ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(620, 290, 90, 20);

        jLabel16.setText("ÇEVRİLEN SONUÇ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(910, 270, 110, 20);

        buttonGroup2.add(rbexcess);
        rbexcess.setText("Sayıyı Excess-3 e çevir");
        getContentPane().add(rbexcess);
        rbexcess.setBounds(780, 240, 150, 23);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("BCD -  EXCESS-3 İŞLEMLERİ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(620, 210, 290, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel18.setText("FATİH MEHMET SAĞIR 1611404039");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(700, 460, 290, 30);

        setBounds(0, 0, 1091, 584);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     /*  
        int a = Integer.parseInt(cevirileceksayi.getText());
        int b = Integer.parseInt(cevirilensayi.getText());
        int c= a+b;
        jLabel1.setText(String.valueOf(c));
        
        if(rb2den10.isSelected()){
        jLabel2.setText(rb2den10.getText());
        }
        else if (jRadioButton2.isSelected()) {
           jLabel2.setText(jRadioButton2.getText());
        }
       */     
        if(rb2den10.isSelected()){ 
    
        String num=cevirileceksayi.getText();// girilecek sayı
        int lenght=num.length(); //girilen sayının uzunluğu
        int sum=0;
        int z;

        for (int i = lenght-1, j=0; i>=0; i--,j++) {
        z=0;
        char letter=num.charAt(i);
        //System.out.println("z: "+z);
        z=(int) (Math.pow(2, j)*Character.getNumericValue(letter) );
        //System.out.println(letter+"  j:"+j+"  z:"+z+"   sum:"+sum);
        sum=sum+z;
        cevirilensayi.setText(String.valueOf(sum));
        }
        }
        else if (rb8den10.isSelected()) {
        String num=cevirileceksayi.getText();// girilecek sayı
         int lenght=num.length(); //girilen sayının uzunluğu
        int ssum=0;
        int z;

        for (int i = lenght-1, j=0; i>=0; i--,j++) {
        z=0;
        char letter=num.charAt(i);
        //System.out.println("z: "+z);
        z=(int) (Math.pow(8, j)*Character.getNumericValue(letter) );
       // System.out.println(letter+"  j:"+j+"  z:"+z+"   sum:"+ssum);
        ssum=ssum+z;
        }
        cevirilensayi.setText(String.valueOf(ssum));
        }

    
         else if (rb16dan10.isSelected()) {
           String num=cevirileceksayi.getText();// girilecek sayı
           int lenght=num.length(); //girilen sayının uzunluğu
           int sum=0;
           int z;
           for (int i = lenght-1, j=0; i>=0; i--,j++) {
           z=0;// her satırın toplamı
           char letter=num.charAt(i);
           if (letter=='A' || letter=='a') {
           z=(int) (10*(Math.pow(16, j)));
           sum=sum+z;
           }
           else if (letter=='B' || letter=='B') {
           z=(int) (11*(Math.pow(16, j)));
           sum=sum+z;
           }
           else if (letter=='C' || letter=='C') {
           z=(int) (12*(Math.pow(16, j)));
           sum=sum+z;
           }
           else if (letter=='D' || letter=='B') {
           z=(int) (13*(Math.pow(16, j)));
           sum=sum+z;
           }
           else if (letter=='E' || letter=='B') {
           z=(int) (14*(Math.pow(16, j)));
           sum=sum+z;
           }
           else if (letter=='F' || letter=='B') {
           z=(int) (15*(Math.pow(16, j)));
           sum=sum+z;
           }  
           else{ 
           //System.out.println("z: "+z);
           z=(int) (Math.pow(16, j)*Character.getNumericValue(letter) );
           sum=sum+z;
              }
            }
            cevirilensayi.setText(String.valueOf(sum)); 
                }


    
    
    
        else if (rb10dan8.isSelected()) {
       /*     
        int sayi, s = 0, i = 0, basamak; // Değişkenlerin tanımlanması
        sayi = Integer.parseInt(cevirileceksayi.getText()); // Sayının girilmesi 
        while (sayi > 0){
         // Çevirme işleminin yapılması   
         basamak = (int)((sayi % 2) * Math.pow(10, i));
         i++;
         sayi = sayi / 2;
         s = s + basamak;
        }
        // Çevrilen sayının ekrana yazdırılması
        cevirilensayi.setText(String.valueOf(s));   */
        int sekizlikSayi = 0, i = 1;
        int sayi = Integer.parseInt(cevirileceksayi.getText());
        while (sayi != 0)
        {
            sekizlikSayi += (sayi % 8) * i;
            sayi /= 8;
            i *= 10;
        }
        cevirilensayi.setText(String.valueOf(sekizlikSayi));
         }
        

            else if (rb10dan2.isSelected()) {
            int sayi = Integer.parseInt(cevirileceksayi.getText());
            //String a=Integer.toString(sayi,2);
            //String a=Integer.toBinaryString(sayi);
            String a=String.format("%4s", 
            Integer.toBinaryString(sayi)).replaceAll(" ", "0");
            cevirilensayi.setText(String.valueOf(a));
        }
    
    
            else if (rb10dan16.isSelected()) {
            int sayi = Integer.parseInt(cevirileceksayi.getText());
            String a=Integer.toHexString(sayi);
            cevirilensayi.setText(String.valueOf(a));
        }
   
    
    
    
    
    
    
    
    
    
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int sayi = Integer.parseInt(tumlemetxt.getText());
        //String a=Integer.toBinaryString(~sayi);
        tumlemesonuctxt.setText(String.valueOf(~sayi));
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int sayi = Integer.parseInt(tumlemetxt.getText());
        //String a=Integer.toBinaryString(~sayi);
        tumlemesonuctxt.setText(String.valueOf(~sayi+1));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String num=sayibir2tbntxt.getText();// girilecek sayı
        int lenght=num.length(); //girilen sayının uzunluğu
        int sum=0;
        int z;

        for (int i = lenght-1, j=0; i>=0; i--,j++) {
        z=0;
        char letter=num.charAt(i);
        //System.out.println("z: "+z);
        z=(int) (Math.pow(2, j)*Character.getNumericValue(letter) );
        //System.out.println(letter+"  j:"+j+"  z:"+z+"   sum:"+sum);
        sum=sum+z;       
        }
        
        String num1=sayiiki2tbntxt.getText();// girilecek sayı
        int lenght1=num1.length(); //girilen sayının uzunluğu
        int sum1=0;
        int z1;

        for (int i1 = lenght-1, j1=0; i1>=0; i1--,j1++) {
        z1=0;
        char letter1=num1.charAt(i1);
        //System.out.println("z: "+z);
        z1=(int) (Math.pow(2, j1)*Character.getNumericValue(letter1) );
        //System.out.println(letter+"  j:"+j+"  z:"+z+"   sum:"+sum);
        sum1=sum1+z1;       
        }
        int sonucc=sum-sum1;
        String a=String.format("%4s", 
            Integer.toBinaryString(sonucc)).replaceAll(" ", "0");
            sonuc2tbntxt.setText(String.valueOf(a));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String num=sayibir2tbntxt.getText();// girilecek sayı
        int lenght=num.length(); //girilen sayının uzunluğu
        int sum=0;
        int z;

        for (int i = lenght-1, j=0; i>=0; i--,j++) {
        z=0;
        char letter=num.charAt(i);
        //System.out.println("z: "+z);
        z=(int) (Math.pow(2, j)*Character.getNumericValue(letter) );
        //System.out.println(letter+"  j:"+j+"  z:"+z+"   sum:"+sum);
        sum=sum+z;       
        }
        
        String num1=sayiiki2tbntxt.getText();// girilecek sayı
        int lenght1=num1.length(); //girilen sayının uzunluğu
        int sum1=0;
        int z1;

        for (int i1 = lenght-1, j1=0; i1>=0; i1--,j1++) {
        z1=0;
        char letter1=num1.charAt(i1);
        //System.out.println("z: "+z);
        z1=(int) (Math.pow(2, j1)*Character.getNumericValue(letter1) );
        //System.out.println(letter+"  j:"+j+"  z:"+z+"   sum:"+sum);
        sum1=sum1+z1;       
        }
        int sonucc=sum+sum1;
        String a=String.format("%4s", 
            Integer.toBinaryString(sonucc)).replaceAll(" ", "0");
            sonuc2tbntxt.setText(String.valueOf(a));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(rbbcd.isSelected()){
           int sayi = Integer.parseInt(bcdgirilentxt.getText());
           String BCD="";
           while(sayi!=0)
           {
           int t=sayi%10;
           String tBCD=Integer.toBinaryString(t);
           while(tBCD.length()<4)
           {
           tBCD="0"+tBCD;
           }
           BCD=tBCD+BCD;
           sayi/=10;
           }
         bcdsonuctxt.setText(BCD);
        }
        else if(rbexcess.isSelected()){
           int sayi = Integer.parseInt(bcdgirilentxt.getText());
           sayi=sayi+3;
           String a=String.format("%4s", 
           Integer.toBinaryString(sayi)).replaceAll(" ", "0");
           bcdsonuctxt.setText(String.valueOf(a)); 
        }
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed
        
        
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yaallahbs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yaallahbs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yaallahbs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yaallahbs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yaallahbs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bcdgirilentxt;
    private javax.swing.JTextField bcdsonuctxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cevirileceksayi;
    private javax.swing.JTextField cevirilensayi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rb10dan16;
    private javax.swing.JRadioButton rb10dan2;
    private javax.swing.JRadioButton rb10dan8;
    private javax.swing.JRadioButton rb16dan10;
    private javax.swing.JRadioButton rb2den10;
    private javax.swing.JRadioButton rb8den10;
    private javax.swing.JRadioButton rbbcd;
    private javax.swing.JRadioButton rbexcess;
    private javax.swing.JTextField sayibir2tbntxt;
    private javax.swing.JTextField sayiiki2tbntxt;
    private javax.swing.JTextField sonuc2tbntxt;
    private javax.swing.JTextField tumlemesonuctxt;
    private javax.swing.JTextField tumlemetxt;
    // End of variables declaration//GEN-END:variables
}
